### PR TITLE
Accessibility implementation 

### PR DESCRIPTION
**Pull request by HossainAraf**
Following methods are implemented :

- Page titles: [Updated the title](https://github.com/HossainAraf/Portfolio-Mobile-First/pull/9/commits/e2dd20b4f689d67c7fe3625d35c1b8eb520aab46)
- Image text alternatives : No issue found
- Text headings: No issue found
- Color contrast: No issue found
- Resize: No issue found
- Interaction : No issue found
- Moving content : [Updated the transition time in order to move the button slowly](https://github.com/HossainAraf/Portfolio-Mobile-First/pull/9/commits/e2dd20b4f689d67c7fe3625d35c1b8eb520aab46)
- The basic structure of the page: No issue found

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @HossainAraf, @BilalLiaquat7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
- [ ] In the result section of your report, please kindly include a statement pertaining to every point checked:

* If everything was ok, you should make a statement about that (e.g. "Page titles - no issues found").
* If issues were found, you should link to the corresponding line of code in the Pull Request changes
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- For future pull requests, please notice that your branch name `accessibility` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-accessibility`. This makes it easier to track the changes and the purpose of each branch.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BilalLiaquat7** [comment]
@topeogunleye 
Can you please let me know what exactly you see as the problem in the above review I didn't see any changes required things except a comments picture, please elaborate then we can make sure from our side.

Thanks

**Comment by topeogunleye** [comment]
> @topeogunleye Can you please let me know what exactly you see as the problem in the above review I didn't see any changes required things except a comments picture, please elaborate then we can make sure from our side.
> 
> Thanks

- [ ] In the result section of your report, please kindly include a statement pertaining to every point checked:
- If everything was ok, then make a statement about that (e.g. "Page titles - no issues found").
- If issues were found, you should link to the corresponding line of code in the Pull Request changes

Example:
image

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @HossainAraf, @BilalLiaquat7 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights
✅ Good PR Title
✅ Good PR Description
✅ Good implementation of GitHub Flows

 ## Required Changes ♻️

- [ ] Well, the visual appearance of your "LET'S CONNECT" social link title is good. However, you have used an "a" tag for the title, which is not appropriate. It's important to use the appropriate heading tag (e.g., h3 to h6) for this title. Please consider replacing the "a" tag with the proper heading tag to ensure better semantic structure and accessibility.

image

- [ ] 👍 Great job on the visual appearance of your button and text! However, it's important to ensure that the button and text meet the Web Content Accessibility Guidelines (WCAG) for contrast ratio. As recommended by WAI, web pages should have a minimum contrast by default, with a contrast ratio of at least 4.5:1 for normal-sized text. Unfortunately, your color combination fails to meet this requirement. To improve accessibility, please consider updating the text color to provide sufficient contrast with the background. You can use online contrast checkers or color contrast accessibility tools to verify if the new color combination meets the required standards. 🎨 Keep up the good work!💪
image
image



_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by brainconnect93 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @HossainAraf , 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 




## To Highlight 👍

- Has a proper Pull Request. ✔️
- Portfolio project accessibility ✔️
- Color contrast ✔️
- Alternative text for images ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
